"""Mission catalog for Mompy.

The learning path is ordered for complete beginners. Each block introduces one
new family of concepts, and missions only ask for concepts already covered by
the guided lesson for that block.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass


PLANNED_TOTAL_MISSIONS = 30


@dataclass(frozen=True)
class Mission:
    id: str
    number: int
    level: int
    block: int
    title: str
    concept: str
    description: str
    objective: str
    starter_code: str
    expected_output: str
    help: str
    expected_concepts: tuple[str, ...]
    xp: int

    def to_dict(self) -> dict:
        data = asdict(self)
        data["expected_concepts"] = list(self.expected_concepts)
        data["starterCode"] = self.starter_code
        data["expectedOutput"] = self.expected_output
        return data


def mission_xp(level: int) -> int:
    """Return progressive mission XP without making early levels too fast."""

    return 35 + max(0, level - 1) * 5


MISSIONS: tuple[Mission, ...] = (
    Mission(
        id="mission_001",
        number=1,
        level=1,
        block=1,
        title="Mission 01 - First Output",
        concept="print",
        description="Primeiro passo: faca o programa escrever uma mensagem no console.",
        objective="Use print() para mostrar exatamente: Hello, Mompy!",
        starter_code="# escreva aqui\n",
        expected_output="Hello, Mompy!",
        help='Use aspas dentro do print: print("Hello, Mompy!")',
        expected_concepts=("print", "string", "quotes", "parentheses"),
        xp=mission_xp(1),
    ),
    Mission(
        id="mission_002",
        number=2,
        level=2,
        block=1,
        title="Mission 02 - Text",
        concept="strings",
        description="Texto em Python fica entre aspas.",
        objective="Mostre exatamente: Python",
        starter_code="# texto precisa de aspas\n",
        expected_output="Python",
        help='Escreva o texto entre aspas dentro de print().',
        expected_concepts=("print", "string", "quotes"),
        xp=mission_xp(2),
    ),
    Mission(
        id="mission_003",
        number=3,
        level=3,
        block=1,
        title="Mission 03 - Parentheses",
        concept="print parentheses",
        description="Comandos como print usam parenteses para receber informacao.",
        objective="Mostre exatamente: Boot ready",
        starter_code="# print precisa abrir e fechar parenteses\n",
        expected_output="Boot ready",
        help='Use print("Boot ready"). Confira aspas e parenteses.',
        expected_concepts=("print", "string", "quotes", "parentheses"),
        xp=mission_xp(3),
    ),
    Mission(
        id="mission_004",
        number=4,
        level=4,
        block=1,
        title="Mission 04 - Another Message",
        concept="output",
        description="A saida do console mostra o texto que o programa escreveu.",
        objective="Mostre exatamente: Mompy",
        starter_code="# mostre uma mensagem simples\n",
        expected_output="Mompy",
        help='Use print("Mompy"). Nao esqueca as aspas.',
        expected_concepts=("print", "string", "output"),
        xp=mission_xp(4),
    ),
    Mission(
        id="mission_005",
        number=5,
        level=5,
        block=1,
        title="Mission 05 - Two Lines",
        concept="two print calls",
        description="Voce pode usar mais de um comando, um em cada linha.",
        objective="Mostre First e depois Second, cada um em uma linha.",
        starter_code="# use dois prints\n",
        expected_output="First\nSecond",
        help='Use dois comandos: print("First") e print("Second").',
        expected_concepts=("print", "string", "multiple commands", "output"),
        xp=mission_xp(5),
    ),
    Mission(
        id="mission_006",
        number=6,
        level=6,
        block=2,
        title="Mission 06 - Variable",
        concept="variables",
        description="Variaveis guardam valores para voce usar depois.",
        objective='Crie name = "Mompy" e depois mostre name com print().',
        starter_code='name = "Mompy"\n',
        expected_output="Mompy",
        help='Depois de criar a variavel, use print(name). Nao coloque name entre aspas no print.',
        expected_concepts=("variable", "assignment", "print", "string"),
        xp=mission_xp(6),
    ),
    Mission(
        id="mission_007",
        number=7,
        level=7,
        block=2,
        title="Mission 07 - Number Value",
        concept="numbers",
        description="Variaveis tambem podem guardar numeros.",
        objective="Crie level = 1 e mostre level.",
        starter_code="level = 1\n",
        expected_output="1",
        help="Use print(level). Numero nao precisa de aspas.",
        expected_concepts=("variable", "assignment", "number", "print"),
        xp=mission_xp(7),
    ),
    Mission(
        id="mission_008",
        number=8,
        level=8,
        block=2,
        title="Mission 08 - Change Value",
        concept="reassignment",
        description="Uma variavel pode receber outro valor mais tarde.",
        objective='Comece com mode = "off", troque para "on" e mostre mode.',
        starter_code='mode = "off"\n',
        expected_output="on",
        help='Atribua mode = "on" antes de usar print(mode).',
        expected_concepts=("variable", "assignment", "reassignment", "print"),
        xp=mission_xp(8),
    ),
    Mission(
        id="mission_009",
        number=9,
        level=9,
        block=2,
        title="Mission 09 - Simple Sum",
        concept="addition",
        description="Python consegue somar numeros guardados em variaveis.",
        objective="Some a e b para mostrar 5.",
        starter_code="a = 2\nb = 3\n",
        expected_output="5",
        help="Use print(a + b).",
        expected_concepts=("variable", "number", "addition", "print"),
        xp=mission_xp(9),
    ),
    Mission(
        id="mission_010",
        number=10,
        level=10,
        block=2,
        title="Mission 10 - Text Variable",
        concept="string variable",
        description="Quando a variavel guarda texto, o print mostra o texto guardado.",
        objective='Guarde "Ready" em message e mostre message.',
        starter_code='message = "Ready"\n',
        expected_output="Ready",
        help="Use print(message), sem aspas em message.",
        expected_concepts=("variable", "string", "assignment", "print"),
        xp=mission_xp(10),
    ),
    Mission(
        id="mission_011",
        number=11,
        level=11,
        block=3,
        title="Mission 11 - If True",
        concept="if",
        description="O if executa um bloco quando a condicao e verdadeira.",
        objective="Use if para mostrar exatamente: Ready",
        starter_code="power = True\n",
        expected_output="Ready",
        help='Use if power: e, dentro dele, print("Ready").',
        expected_concepts=("if", "boolean", "colon", "indentation", "print"),
        xp=mission_xp(11),
    ),
    Mission(
        id="mission_012",
        number=12,
        level=12,
        block=3,
        title="Mission 12 - Greater Than",
        concept="comparison",
        description="Comparacoes geram True ou False para o if decidir.",
        objective="Se temperature for maior que 5, mostre Warm.",
        starter_code="temperature = 10\n",
        expected_output="Warm",
        help='Use if temperature > 5: e dentro dele print("Warm").',
        expected_concepts=("if", "comparison", "greater than", "indentation"),
        xp=mission_xp(12),
    ),
    Mission(
        id="mission_013",
        number=13,
        level=13,
        block=3,
        title="Mission 13 - Equality",
        concept="equality",
        description="Use == para comparar valores. = guarda valor; == compara.",
        objective='Se code for igual a "py", mostre Python.',
        starter_code='code = "py"\n',
        expected_output="Python",
        help='Use if code == "py": e dentro dele print("Python").',
        expected_concepts=("if", "equality", "==", "string", "indentation"),
        xp=mission_xp(13),
    ),
    Mission(
        id="mission_014",
        number=14,
        level=14,
        block=3,
        title="Mission 14 - Else",
        concept="else",
        description="else roda quando a condicao do if nao e verdadeira.",
        objective="Com score = 1, mostre Try again usando if e else.",
        starter_code="score = 1\n",
        expected_output="Try again",
        help='Use if score >= 2: para Pass e else: para print("Try again").',
        expected_concepts=("if", "else", "comparison", "indentation"),
        xp=mission_xp(14),
    ),
    Mission(
        id="mission_015",
        number=15,
        level=15,
        block=3,
        title="Mission 15 - Less Or Equal",
        concept="less or equal",
        description="Comparacoes como <= tambem ajudam o programa a decidir.",
        objective="Se count for menor ou igual a 3, mostre Inside.",
        starter_code="count = 3\n",
        expected_output="Inside",
        help='Use if count <= 3: e dentro dele print("Inside").',
        expected_concepts=("if", "comparison", "<=", "indentation"),
        xp=mission_xp(15),
    ),
    Mission(
        id="mission_016",
        number=16,
        level=16,
        block=4,
        title="Mission 16 - Range Loop",
        concept="for range",
        description="for com range repete um bloco para uma sequencia de numeros.",
        objective="Use range(3) para mostrar 0, 1 e 2.",
        starter_code="for i in range(3):\n    ",
        expected_output="0\n1\n2",
        help="Dentro do for, use print(i). A linha do print precisa ficar indentada.",
        expected_concepts=("for", "range", "loop variable", "indentation", "print"),
        xp=mission_xp(16),
    ),
    Mission(
        id="mission_017",
        number=17,
        level=17,
        block=4,
        title="Mission 17 - Repeat Text",
        concept="repeat text",
        description="O bloco dentro do for roda uma vez para cada volta.",
        objective="Mostre Mompy duas vezes usando for e range.",
        starter_code="for i in range(2):\n    ",
        expected_output="Mompy\nMompy",
        help='Dentro do for, use print("Mompy").',
        expected_concepts=("for", "range", "indentation", "print"),
        xp=mission_xp(17),
    ),
    Mission(
        id="mission_018",
        number=18,
        level=18,
        block=4,
        title="Mission 18 - Start At One",
        concept="range start stop",
        description="range pode receber inicio e fim.",
        objective="Use range(1, 4) para mostrar 1, 2 e 3.",
        starter_code="for number in range(1, 4):\n    ",
        expected_output="1\n2\n3",
        help="Dentro do for, use print(number).",
        expected_concepts=("for", "range", "loop variable", "print"),
        xp=mission_xp(18),
    ),
    Mission(
        id="mission_019",
        number=19,
        level=19,
        block=4,
        title="Mission 19 - Loop Letters",
        concept="string loop",
        description="for tambem pode passar por cada letra de um texto.",
        objective='Mostre as letras de "py", uma por linha.',
        starter_code='for letter in "py":\n    ',
        expected_output="p\ny",
        help="Dentro do for, use print(letter).",
        expected_concepts=("for", "string sequence", "loop variable", "print"),
        xp=mission_xp(19),
    ),
    Mission(
        id="mission_020",
        number=20,
        level=20,
        block=4,
        title="Mission 20 - Loop Sum",
        concept="accumulator",
        description="Um loop pode atualizar uma variavel a cada volta.",
        objective="Some 0, 1 e 2 com for e mostre 3.",
        starter_code="total = 0\nfor number in range(3):\n    ",
        expected_output="3",
        help="Dentro do for, use total = total + number. Depois do for, use print(total).",
        expected_concepts=("for", "range", "variable update", "addition", "print"),
        xp=mission_xp(20),
    ),
    Mission(
        id="mission_021",
        number=21,
        level=21,
        block=5,
        title="Mission 21 - Create List",
        concept="lists",
        description="Listas guardam varios valores em ordem.",
        objective='Crie uma lista com "onion", "terminal" e "python", depois mostre a lista.',
        starter_code="items = []\n",
        expected_output="['onion', 'terminal', 'python']",
        help='Use items = ["onion", "terminal", "python"] e print(items).',
        expected_concepts=("list", "brackets", "items", "commas", "print"),
        xp=mission_xp(21),
    ),
    Mission(
        id="mission_022",
        number=22,
        level=22,
        block=5,
        title="Mission 22 - List Index",
        concept="index",
        description="O primeiro item de uma lista fica no indice 0.",
        objective="Mostre o segundo item da lista.",
        starter_code='items = ["onion", "terminal", "python"]\n',
        expected_output="terminal",
        help="O segundo item e items[1]. Use print(items[1]).",
        expected_concepts=("list", "index", "zero based index", "print"),
        xp=mission_xp(22),
    ),
    Mission(
        id="mission_023",
        number=23,
        level=23,
        block=5,
        title="Mission 23 - Append",
        concept="append",
        description="append adiciona um item ao final de uma lista.",
        objective="Adicione 4 em [1, 2, 3] e mostre a lista.",
        starter_code="numbers = [1, 2, 3]\n",
        expected_output="[1, 2, 3, 4]",
        help="Use numbers.append(4), depois print(numbers).",
        expected_concepts=("list", "append", "number", "print"),
        xp=mission_xp(23),
    ),
    Mission(
        id="mission_024",
        number=24,
        level=24,
        block=5,
        title="Mission 24 - Loop List",
        concept="iterate list",
        description="Voce pode usar for para passar por cada item de uma lista.",
        objective="Mostre cada item da lista, um por linha.",
        starter_code='items = ["onion", "python"]\n',
        expected_output="onion\npython",
        help="Use for item in items: e dentro dele print(item).",
        expected_concepts=("list", "for", "item", "indentation", "print"),
        xp=mission_xp(24),
    ),
    Mission(
        id="mission_025",
        number=25,
        level=25,
        block=5,
        title="Mission 25 - List Length",
        concept="len list",
        description="len conta quantos itens existem em uma lista.",
        objective="Mostre quantos numeros existem na lista.",
        starter_code="numbers = [1, 2, 3]\n",
        expected_output="3",
        help="Use print(len(numbers)).",
        expected_concepts=("list", "len", "items", "print"),
        xp=mission_xp(25),
    ),
    Mission(
        id="mission_026",
        number=26,
        level=26,
        block=6,
        title="Mission 26 - Simple Function",
        concept="functions",
        description="Uma funcao guarda um bloco de codigo com nome.",
        objective='Crie say_hello() para mostrar Hello e depois chame a funcao.',
        starter_code="def say_hello():\n    ",
        expected_output="Hello",
        help='Dentro da funcao use print("Hello"). Depois chame say_hello().',
        expected_concepts=("def", "function", "call", "indentation", "print"),
        xp=mission_xp(26),
    ),
    Mission(
        id="mission_027",
        number=27,
        level=27,
        block=6,
        title="Mission 27 - Parameter",
        concept="parameters",
        description="Parametro e uma informacao que entra na funcao.",
        objective='Crie greet(user) e chame com "Mompy" para mostrar Hello, Mompy.',
        starter_code="def greet(user):\n    ",
        expected_output="Hello, Mompy",
        help='Use print("Hello, " + user) dentro da funcao e depois greet("Mompy").',
        expected_concepts=("def", "parameter", "call", "string concatenation", "print"),
        xp=mission_xp(27),
    ),
    Mission(
        id="mission_028",
        number=28,
        level=28,
        block=6,
        title="Mission 28 - Return",
        concept="return",
        description="return devolve um valor para quem chamou a funcao.",
        objective="Crie add(a, b), retorne a + b e mostre add(2, 3).",
        starter_code="def add(a, b):\n    ",
        expected_output="5",
        help="A funcao deve retornar a + b. Depois use print(add(2, 3)).",
        expected_concepts=("def", "parameters", "return", "addition", "print"),
        xp=mission_xp(28),
    ),
    Mission(
        id="mission_029",
        number=29,
        level=29,
        block=6,
        title="Mission 29 - Return Text",
        concept="return text",
        description="Uma funcao tambem pode devolver texto.",
        objective='Crie make_message(user) e mostre Hello, Mackson.',
        starter_code="def make_message(user):\n    ",
        expected_output="Hello, Mackson",
        help='Retorne "Hello, " + user e depois use print(make_message("Mackson")).',
        expected_concepts=("def", "parameter", "return", "string concatenation", "print"),
        xp=mission_xp(29),
    ),
    Mission(
        id="mission_030",
        number=30,
        level=30,
        block=6,
        title="Mission 30 - Function Result",
        concept="function result",
        description="Funcoes ajudam a organizar uma pequena regra em um nome.",
        objective="Crie double(n), retorne n * 2 e mostre double(4).",
        starter_code="def double(n):\n    ",
        expected_output="8",
        help="Use return n * 2 dentro da funcao. Depois use print(double(4)).",
        expected_concepts=("def", "parameter", "return", "multiplication", "print"),
        xp=mission_xp(30),
    ),
)


MISSIONS_BY_ID: dict[str, Mission] = {mission.id: mission for mission in MISSIONS}


def get_mission(mission_id: str) -> Mission | None:
    return MISSIONS_BY_ID.get(mission_id)


def get_missions() -> list[dict]:
    return [mission.to_dict() for mission in MISSIONS]


def get_current_mission(index: int) -> Mission:
    if index < 0:
        return MISSIONS[0]
    if index >= len(MISSIONS):
        return MISSIONS[-1]
    return MISSIONS[index]
